/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Instance": {                                    "en": "Instance",                                        "de": "Instanz",                                         "ru": "Инстанция",                                       "pt": "Instância",                                       "nl": "Instantie",                                       "fr": "Instance",                                        "it": "Esempio",                                         "es": "Instancia",                                       "pl": "Instancja",                                       "zh-cn": "例"},
    "extraAttr": {                                   "en": "extraAttr",                                       "de": "extraAttr",                                       "ru": "extraAttr",                                       "pt": "extraAttr",                                       "nl": "extraAttr",                                       "fr": "extraAttr",                                       "it": "extraAttr",                                       "es": "extraAttr",                                       "pl": "extraAttr",                                       "zh-cn": "extraAttr"},
    "group_extraMyset": {                            "en": "extraMyset",                                      "de": "extraMyset",                                      "ru": "extraMyset",                                      "pt": "extraMyset",                                      "nl": "extraMyset",                                      "fr": "extraMyset",                                      "it": "extraMyset",                                      "es": "extraMyset",                                      "pl": "extraMyset",                                      "zh-cn": "extraMyset"},
    "htmlText": {                                    "en": "htmlText",                                        "de": "htmlText",                                        "ru": "htmlText",                                        "pt": "htmlText",                                        "nl": "htmlText",                                        "fr": "htmlText",                                        "it": "htmlText",                                        "es": "htmlText",                                        "pl": "htmlText",                                        "zh-cn": "htmlText"},
    "myColor": {                                     "en": "myColor",                                         "de": "meineColor",                                      "ru": "Мой цвет",                                        "pt": "minhaCor",                                        "nl": "mijnKleur",                                       "fr": "maCouleur",                                       "it": "mioColore",                                       "es": "miColor",                                         "pl": "mójKolor",                                        "zh-cn": "我的颜色"},
    "myColor_tooltip": {                             "en": "Description of myColor",                          "de": "Beschreibung von myColor",                        "ru": "Описание myColor",                                "pt": "Descrição de myColor",                            "nl": "Beschrijving van myColor",                        "fr": "Description de myColor",                          "it": "Descrizione di myColor",                          "es": "Descripción de myColor",                          "pl": "Opis myColor",                                    "zh-cn": "myColor的描述"},
    "option1": {                                     "en": "option1",                                         "de": "Option 1",                                        "ru": "Опция 1",                                         "pt": "Opção 1",                                         "nl": "Optie 1",                                         "fr": "Option 1",                                        "it": "opzione 1",                                       "es": "Opción 1",                                        "pl": "opcja 1",                                         "zh-cn": "选项1"},
    "option2": {                                     "en": "option2",                                         "de": "Option 2",                                        "ru": "option2",                                         "pt": "opção 2",                                         "nl": "Optie 2",                                         "fr": "Option 2",                                        "it": "opzione 2",                                       "es": "opcion 2",                                        "pl": "Opcja 2",                                         "zh-cn": "选项2"},
    "philips-air adapter settings": {                "en": "Adapter settings for philips-air",                "de": "Adaptereinstellungen für philips-air",            "ru": "Настройки адаптера для philips-air",              "pt": "Configurações do adaptador para philips-air",     "nl": "Adapterinstellingen voor philips-air",            "fr": "Paramètres d'adaptateur pour philips-air",        "it": "Impostazioni dell'adattatore per philips-air",    "es": "Ajustes del adaptador para philips-air",          "pl": "Ustawienia adaptera dla philips-air",             "zh-cn": "philips-air的适配器设置"},
};